// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7-ysNdDvM3bQCx9p66B2LU6lUzoTd5Hs',
    appId: '1:318190260193:web:3d15cbca75a2566106cca0',
    messagingSenderId: '318190260193',
    projectId: 'vchd-tablo-new',
    authDomain: 'vchd-tablo-new.firebaseapp.com',
    storageBucket: 'vchd-tablo-new.appspot.com',
    measurementId: 'G-DX0MCHTEXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo6uUW6daAx_VoPgeismasRv-jBgD4fvk',
    appId: '1:318190260193:android:983131fe12136f8806cca0',
    messagingSenderId: '318190260193',
    projectId: 'vchd-tablo-new',
    storageBucket: 'vchd-tablo-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlcgqDbvrgJOvddsIfIddsMVRKi9YVwRI',
    appId: '1:318190260193:ios:79b712dc0740616c06cca0',
    messagingSenderId: '318190260193',
    projectId: 'vchd-tablo-new',
    storageBucket: 'vchd-tablo-new.appspot.com',
    iosBundleId: 'com.example.vchdTablo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlcgqDbvrgJOvddsIfIddsMVRKi9YVwRI',
    appId: '1:318190260193:ios:79b712dc0740616c06cca0',
    messagingSenderId: '318190260193',
    projectId: 'vchd-tablo-new',
    storageBucket: 'vchd-tablo-new.appspot.com',
    iosBundleId: 'com.example.vchdTablo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7-ysNdDvM3bQCx9p66B2LU6lUzoTd5Hs',
    appId: '1:318190260193:web:a3ba82c7bc56500f06cca0',
    messagingSenderId: '318190260193',
    projectId: 'vchd-tablo-new',
    authDomain: 'vchd-tablo-new.firebaseapp.com',
    storageBucket: 'vchd-tablo-new.appspot.com',
    measurementId: 'G-M3SJ63G0PV',
  );
}
